services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                UID: ${UID-1000}
                GID: ${GID-1000}
        image: laravel-app:dev
        container_name: laravel_app
        restart: unless-stopped
        volumes:
            - ./:/var/www/html:cached
        environment:
            APP_ENV: local
            APP_DEBUG: "true"
        depends_on:
            - db
            - redis

    web:
        image: nginx:1.27-alpine
        container_name: laravel_web
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html:cached
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_USER: ${DB_USERNAME:-laravel}
            MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"

    redis:
        image: redis:7-alpine
        container_name: laravel_redis
        restart: unless-stopped
        ports:
            - "6379:6379"

    node:
        image: node:20-alpine
        container_name: laravel_node
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html:cached
        command: sh -c "npm install && npm run dev -- --host"
        ports:
            - "5173:5173"

    mailpit:
        image: axllent/mailpit:latest
        container_name: laravel_mailpit
        restart: unless-stopped
        ports:
            - "8025:8025"
            - "1025:1025"

volumes:
    dbdata:
